name: CI Deploy PROD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  server:
    name: Deploy Server APIs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install-Test
        run: |
          yarn install --frozen-lockfile
          yarn test

      - name: Install SAM
        uses: aws-actions/setup-sam@v2

      - name: Validate SAM template
        run: .deploy/aws-sam-validate.sh samconfig-prod.toml

      - name: Build
        run: yarn build

      - name: Deploy Stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ROLE: CIDeployAccess
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
          AWS_BUCKET_NAME: ds-customer-api-prod
          AWSENV: prod
        run: |
          .deploy/aws-sam-deploy.sh samconfig-prod.toml
